# Generated by Django 4.2.11 on 2024-04-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer',
            new_name='user',
        ),
    ]
