# Generated by Django 4.2.11 on 2024-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contactus_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='additional_comments',
            field=models.TextField(null=True),
        ),
    ]
