# Generated by Django 4.2.11 on 2024-05-11 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Name', max_length=200)),
                ('last_name', models.CharField(default='Surname', max_length=200)),
                ('email', models.EmailField(default='example@example.com', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('places', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cancel', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approval', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_guest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
