# Generated by Django 4.2.11 on 2024-03-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cancel_booking',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
