# Generated by Django 4.2.11 on 2024-04-07 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_rename_cancel_booking_booking_guest_booking_cancel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='places',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
