# Generated by Django 4.2.11 on 2024-05-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0002_alter_booking_options_booking_created_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_on"]},
        ),
    ]
