# Generated by Django 4.2.11 on 2024-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0005_remove_booking_guest_booking_email_booking_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='Surname', max_length=200),
        ),
    ]
