# Generated by Django 4.2.11 on 2024-04-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0007_booking_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
