# Generated by Django 4.2.11 on 2024-04-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_info', '0002_rename_customer_profile_user'),
        ('booking_system', '0009_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_info.profile'),
        ),
    ]
